# Generated by Django 4.2.3 on 2023-07-30 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_image_1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_images'),
            preserve_default=False,
        ),
    ]
